on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_GITHUB_SECRET_effc}}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n abcde123 -g abcde123afaf-rg --location "South Central US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n abcde123 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n abcde123 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n abcde123 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: abcde123.azurecr.io
        username: ${{steps.create-acr.outputs.acr_username}}
        password: ${{steps.create-acr.outputs.acr_password}}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/go/plain/container/Application" -f  "go/plain/container/Application/Dockerfile" -t abcde123.azurecr.io/aaaatiwarishubakseffc:${{github.sha}}
        docker push abcde123.azurecr.io/aaaatiwarishubakseffc:${{github.sha}}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{secrets.aks_aaaatiwarishubaks_kubeConfig}}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aaaatiwarishubakseffc | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aaaatiwarishubakseffc`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aaaatiwarishubakseffc
        container-registry-url: abcde123.azurecr.io
        container-registry-username: ${{steps.create-acr.outputs.acr_username}}
        container-registry-password: ${{steps.create-acr.outputs.acr_password}}
        secret-name: aaaatiwarishdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aaaatiwarishubakseffc
        manifests: |
          go/plain/container/Application/manifests/deployment-effc.yml
          go/plain/container/Application/manifests/service-effc.yml
        images: |
          abcde123.azurecr.io/aaaatiwarishubakseffc:${{github.sha}}
        imagepullsecrets: |
          aaaatiwarishdockerauth