# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#               echo $TEMP_DIRECTORY
#               echo $GITHUB_ENV
#               echo $CONTAINER_TEMP_DIRECTORY
      - name: set variable
        run: |
              echo "keyname=keyvalue" >> $GITHUB_ENV
          
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.0
        with:
          # Specify the script here
          inlineScript: |
                        echo "hi"
                        echo $keyname
                        echo ${CONTAINER_TEMP_DIRECTORY}
                        echo "hb"
                        echo ${TEMP_DIRECTORY}
                        echo $GITHUB_WORKSPACE
                        echo "wspace"
                        echo ${GITHUB_WORKSPACE}


#           # Azure CLI version to be used to execute the script. If not provided, latest version is used
#           azcliversion: # optional, default is latest
