on: [push]
name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: Azure/arm-deploy@v1
      id: deployaction1
      with:
        scope: resourcegroup
        resourceGroupName: kptest
        subscriptionId: c00d16c7-6c1f-4c03-9be1-6934a4c49682
        template: examples/template/template.json
        parameters: examples/template/parameters.json
        deploymentMode: incremental
    
    - run: echo ${{ steps.deployaction1.outputs.containerName }}
