on: [push]
name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: kpTestOrg/ARMtesting@master
      id: deploy
      with:
        scope: resourcegroup
        templateLocation: examples/template/template.json
        parameters: examples/template/parameters.json
