on: [push]
name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: arm-action-private/arm@master
      id: deploy
      with:
        scope: subscription
        subscriptionId: c00d16c7-6c1f-4c03-9be1-6934a4c49682
        location: centralus
        templateLocation: examples/template/template.json
        parameters: examples/template/parameters.json
