on: [push]
name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: kpTestOrg/ARMtesting@master
      id: deployaction1
      with:
        scope: resourcegroup
        resourceGroupName: demoResourceGroup
        subscriptionId: 393a91ee-f98d-43ff-b964-009bda0fdf2e
        template: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-webapp-basic-linux/azuredeploy.json
        parameters: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-webapp-basic-linux/azuredeploy.parameters.json
        deploymentMode: incremental
    
    - run: echo ${{ steps.deployaction1.outputs.containerName }}
