on: [push]
name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/arm-deploy@v1
      id: deployaction
      with:
        scope: managementgroup
        managementGroupId: kptestnewmg101
        region: WestUS
        templates: https://kpteststorage0.blob.core.windows.net/kptestcontainer/mgtemp.json
        parameters: https://kpteststorage0.blob.core.windows.net/kptestcontainer/mgparam.json

