on: [push]
name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: kpTestOrg/ARMtesting@master
      id: deployaction1
      with:
        scope: managementgroup
        managementgroupid: E2eTestGroupForArmAction
        region: WestUS
        template: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/managementgroup-deployments/mg-policy/azuredeploy.json
        parameters: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/managementgroup-deployments/mg-policy/azuredeploy.parameters.json
    
