on: [push]
name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: kpTestOrg/ARMTesting@master
      id: deployaction1
      with:
        scope: managementgroup
        managementgroupid: kptestmg
        region: West US
        template: examples/template/template.json
        parameters: examples/template/parameters.json
