on: [push]
name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: kanika1894/tempforARM@master
      id: deploy
      with:
        scope: resourcegroup
        resourceGroupName: kptest2
        templateLocation: examples/template/template.json
        parameters: webAppName=nownewapp
