on: [push]
name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: whiteducksoftware/azure-arm-action-js@v3
      with:
        resourceGroupName: kptest2
        templateLocation: examples/template/template.json
        
